Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -24,7 +24,9 @@ jobs:
         distribution: 'temurin'
     # Gradle 실행 권한 부여
     - name: Grant permission for gradlew
-      run: chmod +x ./gradlew
+      run: |
+        cd up-down/upProject
+        chmod +x ./gradlew || echo "gradlew file not found"
     # Gradle Build (테스트 생략)
     - name: Build with Gradle
       run: |
